# Which branches are allowed to be released from
allow-branch = ["main"]

sign-commit = true
sign-tag = true

# When releasing a workspace, use a single commit for the pre-release version bump.
# Commit settings will be read from the workspace-config.
consolidate-commits = true

pre-release-commit-message = "chore(release): v{{version}}"
tag-message = "chore(release): v{{version}}"
tag-name = "v{{version}}"

enable-all-features = true

# Publish manually to crates.io
publish = false
