edition = "2024"

# General
newline_style = "Unix"
hex_literal_case = "Lower"

# Imports
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"

# Code block
use_try_shorthand = true
remove_nested_parens = true

# Comments and Docs
normalize_comments = true
normalize_doc_attributes = true

# Reorder
reorder_modules = true

# Enums and Structs
reorder_impl_items = true
use_field_init_shorthand = true
enum_discrim_align_threshold = 40
# struct_field_align_threshold = 40
